In [1]:
import numpy as np

### Matriz Unidimensional

In [2]:
# Criando matriz com uma dimensão
matriz = np.array([1,2,3,4,5])
matriz

array([1, 2, 3, 4, 5])

In [3]:
type(matriz)

numpy.ndarray

### Matriz Bidimensional

In [4]:
# Criando matriz com duas dimensões (2x2)
matriz = np.array([[1,2,],[5,6]])
matriz

array([[1, 2],
       [5, 6]])

### Testando indexação

#### Pegando o item a22 ( de valor 6) da Matriz

In [5]:
# A numpy array (assim como uma lista python comum) inicia com index zero
matriz[1][1]

6

In [6]:
# Pegando primeira linha
matriz[0,:]

array([1, 2])

In [7]:
# Pegando segunda linha
matriz[1,:]

array([5, 6])

In [8]:
# pegando primeira coluna 
matriz[:,0]

array([1, 5])

In [9]:
# pegando segunda coluna 
matriz[:,1]

array([2, 6])

#### Matriz transposta

In [10]:
matriz

array([[1, 2],
       [5, 6]])

In [11]:
matriz.transpose()

array([[1, 5],
       [2, 6]])

### Operações Basicas com Arrays

In [12]:
# Criando arrays com numeros pares
pares = np.array([[0,2,4], [6,8,10]])
pares

array([[ 0,  2,  4],
       [ 6,  8, 10]])

In [13]:
# Criando arrays com numeros ímpares
impares = np.array([[1,3,5],[7,9,11]])
impares

array([[ 1,  3,  5],
       [ 7,  9, 11]])

#### Operação de Soma

In [14]:
# Somando array de números ímpares com a array de numeros pares
pares + impares

array([[ 1,  5,  9],
       [13, 17, 21]])

#### Operação de Subtração

In [15]:
# Subtraindo array de números pares com a array de numeros ímpares
impares - pares

array([[1, 1, 1],
       [1, 1, 1]])